#!/usr/bin/env python3
"""Convert a BDF bitmap font into an Adafruit GFX font header (GFXfont).

    python tools/bdf2gfx.py tools/fonts/5x7.bdf Font5x7 > src/fonts/Font5x7.h

Only printable ASCII (0x20-0x7E) is converted. Glyph bitmaps are packed row-major, MSB first,
continuous across rows, which is the layout Adafruit_GFX expects. The header also defines
<Name>_ASCENT: the number of pixel rows above the baseline, so a row whose top is y is drawn with
the cursor at y + <Name>_ASCENT.
"""
import sys

FIRST, LAST = 0x20, 0x7E


def load(path):
    glyphs = {}
    ascent = None
    cur = None
    lines = open(path, encoding="latin-1").read().splitlines()
    i = 0
    while i < len(lines):
        words = lines[i].split()
        if not words:
            i += 1
            continue
        key = words[0]
        if key == "FONT_ASCENT":
            ascent = int(words[1])
        elif key == "STARTCHAR":
            cur = {}
        elif key == "ENCODING":
            cur["enc"] = int(words[1])
        elif key == "DWIDTH":
            cur["dwidth"] = int(words[1])
        elif key == "BBX":
            cur["bbx"] = tuple(int(w) for w in words[1:5])
        elif key == "BITMAP":
            rows = []
            i += 1
            while lines[i].strip() != "ENDCHAR":
                hexrow = lines[i].strip()
                rows.append((int(hexrow, 16), len(hexrow) * 4))
                i += 1
            cur["rows"] = rows
            glyphs[cur["enc"]] = cur
        i += 1
    return glyphs, ascent


def main():
    path, name = sys.argv[1], sys.argv[2]
    glyphs, ascent = load(path)
    bits = []
    table = []
    top = 0   # highest ink row above the baseline, over all glyphs
    for code in range(FIRST, LAST + 1):
        g = glyphs.get(code)
        if g is None:
            table.append((len(bits) // 8, 0, 0, 0, 0, 0, code))
            continue
        w, h, xo, yo = g["bbx"]
        offset = len(bits)
        for value, nbits in g["rows"][:h]:
            for k in range(w):
                bits.append((value >> (nbits - 1 - k)) & 1)
        while len(bits) % 8:
            bits.append(0)   # each glyph starts on a byte boundary
        top = max(top, yo + h)
        table.append((offset // 8, w, h, g["dwidth"], xo, -(yo + h), code))

    data = [int("".join(str(b) for b in bits[i:i + 8]), 2) for i in range(0, len(bits), 8)]
    out = [f"// Generated by tools/bdf2gfx.py from {path.split('/')[-1]}. Do not edit.",
           "#pragma once",
           "#include <Adafruit_GFX.h>",
           "",
           f"#define {name}_ASCENT {top}",
           "",
           f"const uint8_t {name}Bitmaps[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        out.append("  " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    out.append("};")
    out.append("")
    out.append(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")
    for off, w, h, adv, xo, yo, code in table:
        ch = chr(code)
        label = {"\\": "backslash", "'": "quote"}.get(ch, ch)
        out.append(f"  {{{off:5d}, {w}, {h}, {adv}, {xo:2d}, {yo:3d}}},   // 0x{code:02X} {label}")
    out.append("};")
    out.append("")
    out.append(f"const GFXfont {name} PROGMEM = {{(uint8_t *){name}Bitmaps, (GFXglyph *){name}Glyphs, "
               f"0x{FIRST:02X}, 0x{LAST:02X}, 8}};")
    print("\n".join(out))


if __name__ == "__main__":
    main()
